## Find similarity among documents

In [3]:
import pandas as pd
import numpy as np

In [4]:
def formDictionary(textfile):
    puntulation=''',.?/><\|"';:~`!@#$%^&*()_-+='''
    with open(f'{textfile}', 'r') as f:
        s = f.read()
        mystring= s.split()

    dictionary={}
    for ele in mystring:
        if ele[-1] in puntulation:
            ele = ele[0:len(ele)-1]
        if ele in dictionary:
            dictionary[ele] += 1
        else:
            dictionary.update({ele:1})
    
    return dictionary

In [7]:
dictionary1 = formDictionary('doc1.txt')
print("\ndoc1 : ", dictionary1)
dictionary2 = formDictionary('doc2.txt')
print("\ndoc2 : ", dictionary2)
dictionary3 = formDictionary('doc3.txt')
print("\ndoc3 : ", dictionary3)
dictionary4 = formDictionary('doc4.txt')
print("\ndoc4 : ", dictionary4)
dictionary5 = formDictionary('doc5.txt')
print("\ndoc5 : ", dictionary5)

dictionaries = [dictionary1, dictionary2, dictionary3, dictionary4, dictionary5]

# Create a set of unique words from all dictionaries
all_words = set(word for dictionary in dictionaries for word in dictionary.keys())

# Initialize a matrix with zeros
word_freq_matrix = np.zeros((len(dictionaries), len(all_words)))

# Fill in the matrix with word frequencies
for i, dictionary in enumerate(dictionaries):
    for j, word in enumerate(all_words):
        matrix[i, j] = dictionary.get(word, 0)

# Print the matrix
print("\n")
print(word_freq_matrix)


doc1 :  {'The': 1, 'quick': 1, 'brown': 1, 'fox': 1, 'jumps': 1, 'over': 1, 'the': 1, 'lazy': 1, 'dog': 1, 'This': 1, 'is': 1, 'a': 1, 'test': 1, 'document': 1, 'for': 1, 'cosine': 1, 'similarity': 1}

doc2 :  {'A': 1, 'red': 1, 'apple': 1, 'hangs': 1, 'from': 1, 'a': 1, 'tree': 1, 'branch': 1, 'This': 1, 'document': 1, 'is': 1, 'meant': 1, 'to': 1, 'showcase': 1, 'cosine': 1, 'similarity': 1, 'in': 1, 'action': 1}

doc3 :  {'Cosine': 1, 'similarity': 2, 'is': 2, 'a': 1, 'measure': 1, 'of': 1, 'between': 1, 'two': 1, 'non-zero': 1, 'vectors': 1, 'It': 1, 'often': 1, 'used': 1, 'in': 1, 'natural': 1, 'language': 1, 'processing': 1}

doc4 :  {'Machine': 1, 'learning': 1, 'is': 1, 'a': 1, 'subset': 1, 'of': 1, 'artificial': 1, 'intelligence': 1, 'It': 1, 'involves': 1, 'training': 1, 'models': 1, 'on': 1, 'data': 1, 'to': 1, 'make': 1, 'predictions': 1, 'or': 1, 'decisions': 1}

doc5 :  {'Python': 1, 'is': 1, 'a': 2, 'popular': 1, 'programming': 1, 'language': 1, 'known': 1, 'for': 1, 'i

In [12]:
from sklearn.metrics.pairwise import cosine_similarity
# Initialize an empty similarity matrix of size [numdocs][numdocs]
num_rows = word_freq_matrix.shape[0]
similarity_matrix = np.zeros((num_rows, num_rows))

# Calculate cosine similarity between all pairs of rows / docs
for i in range(num_rows):
    for j in range(i, num_rows):
        # Calculate the cosine similarity using numpy's dot product and euclidean norms
        similarity = np.dot(word_freq_matrix[i], word_freq_matrix[j]) / (np.linalg.norm(word_freq_matrix[i]) * np.linalg.norm(word_freq_matrix[j]))
        # Fill both sides of the symmetric similarity matrix
        similarity_matrix[i, j] = round(similarity, 2)
        similarity_matrix[j, i] = round(similarity, 2)

print("Similarity Matrix : \n\n", similarity_matrix)

Similarity Matrix : 

 [[1.   0.34 0.25 0.11 0.18]
 [0.34 1.   0.29 0.16 0.13]
 [0.25 0.29 1.   0.24 0.27]
 [0.11 0.16 0.24 1.   0.25]
 [0.18 0.13 0.27 0.25 1.  ]]
